name = "test-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "test-email"		#d1数据库名字
database_id = "e65f099d-796d-4eaa-8dff-529b368b20db"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "9be10cd058e04c55b526f8c0c116f50c"					#kv数据库id

#(可选)
#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = "test-email"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


[vars]
orm_log = false
domain = ["example.com"]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
admin = "admin@example.com"				#管理员的邮箱	示例: admin@example.com
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"			#jwt令牌的密钥,随便填一串字符串

[build]
command = "npm --prefix ../mail-vue install && npm --prefix ../mail-vue run build"
