name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#D1 binding name, keep default
database_name = "email"		#D1 database name
database_id = "d14754af-9ce7-477b-ac93-51299dd17a9f"		#D1 database id

[[kv_namespaces]]
binding = "kv"			#KV binding name, keep default
id = "2c708db681cd4335a80f4059bf072840"					#KV namespace id

[assets]
binding = "assets"		#Static asset binding name, keep default
directory = "./dist"	#Frontend Vue build output directory, default dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#Cron runs daily at midnight


#[vars]
#orm_log = false
#domain = []				#Multiple mail domains supported, example: ["example1.com","example2.com"]
#admin = ""				#Admin email example: admin@example.com
#jwt_secret = ""			#JWT secret key, set a long random string

[build]
command = "npm --prefix ../mail-vue install && npm --prefix ../mail-vue run build"
